// Generated by LiveScript 1.4.0
(function(){
  var express, app, port;
  express = require('express');
  app = express();
  app.use(express['static'](__dirname + "/dist"));
  app.listen(port = process.env.port || 8088);
  console.log("The web server has started... port:" + port);
}).call(this);
